### ISSUE TITLE
作者你好

### ISSUE THREAD

**Issue by daonidedie** [gameloft9/layui-admin#2]
请问一下，用什么方式打开能够正常运行啊？

**Comment by gameloft9** [comment]
> 请问一下，用什么方式打开能够正常运行啊？

你好！现在项目已经重新用spring-boot方式实现了，后端工程可打包后用spring-boot方式启动，前端工程既可以放在nginx上面单独部署，也可以放在webapp下面当作一个工程，直接访问，例如：http://xxx.xxx.xxx.xxx:xxxx/manager/layuicms/login.html
