### ISSUE TITLE
申请商业化二开许可

### ISSUE THREAD

**Issue by weiyuming** [gameloft9/layui-admin#4]
你好，

我再CSDN看到了你的这个项目，感觉很适合我这样的后端开发使用，我想在你这个的基础上进行二次开发，目前用于自己学习，后期可能会用在公司的项目上，进行商业化，是否可以给个许可。

如果需要深度可以联系我，我的邮箱  weiyumings@163.com

没有找到您的邮箱，很抱歉用这种方式联系你

**Comment by gameloft9** [comment]
> 你好，
> 
> 我再CSDN看到了你的这个项目，感觉很适合我这样的后端开发使用，我想在你这个的基础上进行二次开发，目前用于自己学习，后期可能会用在公司的项目上，进行商业化，是否可以给个许可。
> 
> 如果需要深度可以联系我，我的邮箱 [weiyumings@163.com](mailto:weiyumings@163.com)
> 
> 没有找到您的邮箱，很抱歉用这种方式联系你
你好！本项目采用MIT协议开源，在项目中注明出处、作者即可。
