### ISSUE TITLE
新增用户登录密码错误问题

### ISSUE THREAD

**Issue by weiyuming** [gameloft9/layui-admin#5]
新增用户时默认密码为123456，使用明文直接存了数据库，但是登陆的时候  将123456使用sha1进行了加密（编码），导致新增的用户因密码失败无法登陆

**Comment by gameloft9** [comment]
> 新增用户时默认密码为123456，使用明文直接存了数据库，但是登陆的时候 将123456使用sha1进行了加密（编码），导致新增的用户因密码失败无法登陆

--------------
已处理。
